// <auto-generated />
using System;
using GeneradoNominaSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeneradoNominaSystem.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260909224004_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.ConceptoNomina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AfectaBase")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsPorcentaje")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormulaCalculo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PorcentajeBase")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiereBase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subtipo")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ConceptosNomina", (string)null);
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.Cotizacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteDocumento")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteEmail")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteTelefono")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaVigencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroCotizacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlantillaCotizacionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlantillaCotizacionId");

                    b.HasIndex("EmpresaId", "NumeroCotizacion")
                        .IsUnique();

                    b.ToTable("Cotizaciones", (string)null);
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.DetalleCotizacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CotizacionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DescuentoPorcentaje")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProductoServicioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CotizacionId");

                    b.HasIndex("ProductoServicioId");

                    b.ToTable("DetallesCotizacion", (string)null);
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.DetalleNomina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Cantidad")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConceptoNominaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NominaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConceptoNominaId");

                    b.HasIndex("NominaId");

                    b.ToTable("DetallesNomina", (string)null);
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Formato")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GeneradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReferenciaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Documentos", (string)null);
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.Empleado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Departamento")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoContrato")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "NumeroDocumento")
                        .IsUnique();

                    b.ToTable("Empleados", null, t =>
                        {
                            t.Property("Departamento")
                                .HasColumnName("Empleado_Departamento");
                        });
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoRuta")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nit")
                        .IsUnique();

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.Nomina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmpleadoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaCalculo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PeriodoNominaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlantillaNominaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("PeriodoNominaId");

                    b.HasIndex("PlantillaNominaId");

                    b.ToTable("Nominas", (string)null);
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.PeriodoNomina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("PeriodosNomina", (string)null);
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.PlantillaConcepto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConceptoNominaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Obligatorio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlantillaNominaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConceptoNominaId");

                    b.HasIndex("PlantillaNominaId");

                    b.ToTable("PlantillasConcepto", (string)null);
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.PlantillaCotizacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("PlantillasCotizacion", (string)null);
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.PlantillaNomina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("PlantillasNomina", (string)null);
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.ProductoServicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("ProductosServicios", (string)null);
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.ConceptoNomina", b =>
                {
                    b.OwnsOne("GeneradoNominaSystem.Domain.ValueObjects.Dinero", "ValorFijo", b1 =>
                        {
                            b1.Property<Guid>("ConceptoNominaId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("ValorFijo_Moneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ValorFijo_Monto");

                            b1.HasKey("ConceptoNominaId");

                            b1.ToTable("ConceptosNomina");

                            b1.WithOwner()
                                .HasForeignKey("ConceptoNominaId");
                        });

                    b.Navigation("ValorFijo");
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.Cotizacion", b =>
                {
                    b.HasOne("GeneradoNominaSystem.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeneradoNominaSystem.Domain.Entities.PlantillaCotizacion", null)
                        .WithMany()
                        .HasForeignKey("PlantillaCotizacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("GeneradoNominaSystem.Domain.ValueObjects.Dinero", "Subtotal", b1 =>
                        {
                            b1.Property<Guid>("CotizacionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("Subtotal_Moneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Subtotal_Monto");

                            b1.HasKey("CotizacionId");

                            b1.ToTable("Cotizaciones");

                            b1.WithOwner()
                                .HasForeignKey("CotizacionId");
                        });

                    b.OwnsOne("GeneradoNominaSystem.Domain.ValueObjects.Dinero", "TotalDescuentos", b1 =>
                        {
                            b1.Property<Guid>("CotizacionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("TotalDescuentos_Moneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalDescuentos_Monto");

                            b1.HasKey("CotizacionId");

                            b1.ToTable("Cotizaciones");

                            b1.WithOwner()
                                .HasForeignKey("CotizacionId");
                        });

                    b.OwnsOne("GeneradoNominaSystem.Domain.ValueObjects.Dinero", "TotalNeto", b1 =>
                        {
                            b1.Property<Guid>("CotizacionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("TotalNeto_Moneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalNeto_Monto");

                            b1.HasKey("CotizacionId");

                            b1.ToTable("Cotizaciones");

                            b1.WithOwner()
                                .HasForeignKey("CotizacionId");
                        });

                    b.Navigation("Subtotal")
                        .IsRequired();

                    b.Navigation("TotalDescuentos")
                        .IsRequired();

                    b.Navigation("TotalNeto")
                        .IsRequired();
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.DetalleCotizacion", b =>
                {
                    b.HasOne("GeneradoNominaSystem.Domain.Entities.Cotizacion", null)
                        .WithMany("Detalles")
                        .HasForeignKey("CotizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeneradoNominaSystem.Domain.Entities.ProductoServicio", null)
                        .WithMany()
                        .HasForeignKey("ProductoServicioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("GeneradoNominaSystem.Domain.ValueObjects.Dinero", "PrecioUnitario", b1 =>
                        {
                            b1.Property<Guid>("DetalleCotizacionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("PrecioUnitario_Moneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PrecioUnitario_Monto");

                            b1.HasKey("DetalleCotizacionId");

                            b1.ToTable("DetallesCotizacion");

                            b1.WithOwner()
                                .HasForeignKey("DetalleCotizacionId");
                        });

                    b.OwnsOne("GeneradoNominaSystem.Domain.ValueObjects.Dinero", "Subtotal", b1 =>
                        {
                            b1.Property<Guid>("DetalleCotizacionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("Subtotal_Moneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Subtotal_Monto");

                            b1.HasKey("DetalleCotizacionId");

                            b1.ToTable("DetallesCotizacion");

                            b1.WithOwner()
                                .HasForeignKey("DetalleCotizacionId");
                        });

                    b.Navigation("PrecioUnitario")
                        .IsRequired();

                    b.Navigation("Subtotal")
                        .IsRequired();
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.DetalleNomina", b =>
                {
                    b.HasOne("GeneradoNominaSystem.Domain.Entities.ConceptoNomina", null)
                        .WithMany()
                        .HasForeignKey("ConceptoNominaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeneradoNominaSystem.Domain.Entities.Nomina", null)
                        .WithMany("Detalles")
                        .HasForeignKey("NominaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GeneradoNominaSystem.Domain.ValueObjects.Dinero", "Valor", b1 =>
                        {
                            b1.Property<Guid>("DetalleNominaId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("Valor_Moneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Valor_Monto");

                            b1.HasKey("DetalleNominaId");

                            b1.ToTable("DetallesNomina");

                            b1.WithOwner()
                                .HasForeignKey("DetalleNominaId");
                        });

                    b.Navigation("Valor")
                        .IsRequired();
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.Documento", b =>
                {
                    b.HasOne("GeneradoNominaSystem.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.Empleado", b =>
                {
                    b.HasOne("GeneradoNominaSystem.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("GeneradoNominaSystem.Domain.ValueObjects.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("EmpleadoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Ciudad")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("TEXT")
                                .HasColumnName("Ciudad");

                            b1.Property<string>("CodigoPostal")
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("CodigoPostal");

                            b1.Property<string>("Departamento")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("TEXT")
                                .HasColumnName("Departamento");

                            b1.Property<string>("DireccionCompleta")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("TEXT")
                                .HasColumnName("Direccion");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("Pais");

                            b1.HasKey("EmpleadoId");

                            b1.ToTable("Empleados");

                            b1.WithOwner()
                                .HasForeignKey("EmpleadoId");
                        });

                    b.OwnsOne("GeneradoNominaSystem.Domain.ValueObjects.Dinero", "SalarioBase", b1 =>
                        {
                            b1.Property<Guid>("EmpleadoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("SalarioBase_Moneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("SalarioBase_Monto");

                            b1.HasKey("EmpleadoId");

                            b1.ToTable("Empleados");

                            b1.WithOwner()
                                .HasForeignKey("EmpleadoId");
                        });

                    b.Navigation("Direccion");

                    b.Navigation("SalarioBase")
                        .IsRequired();
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.Empresa", b =>
                {
                    b.OwnsOne("GeneradoNominaSystem.Domain.ValueObjects.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("EmpresaId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Ciudad")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("TEXT")
                                .HasColumnName("Ciudad");

                            b1.Property<string>("CodigoPostal")
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("CodigoPostal");

                            b1.Property<string>("Departamento")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("TEXT")
                                .HasColumnName("Departamento");

                            b1.Property<string>("DireccionCompleta")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("TEXT")
                                .HasColumnName("Direccion");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("Pais");

                            b1.HasKey("EmpresaId");

                            b1.ToTable("Empresas");

                            b1.WithOwner()
                                .HasForeignKey("EmpresaId");
                        });

                    b.OwnsOne("GeneradoNominaSystem.Domain.ValueObjects.DatosFiscales", "DatosFiscales", b1 =>
                        {
                            b1.Property<Guid>("EmpresaId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("DigitoVerificacion")
                                .HasMaxLength(5)
                                .HasColumnType("TEXT")
                                .HasColumnName("DigitoVerificacion");

                            b1.Property<string>("Nit")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("NitFiscal");

                            b1.Property<string>("RazonSocial")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("TEXT")
                                .HasColumnName("RazonSocialFiscal");

                            b1.Property<string>("RegimenTributario")
                                .HasMaxLength(150)
                                .HasColumnType("TEXT")
                                .HasColumnName("RegimenTributario");

                            b1.Property<string>("RepresentanteLegal")
                                .HasMaxLength(250)
                                .HasColumnType("TEXT")
                                .HasColumnName("RepresentanteLegal");

                            b1.Property<bool>("ResponsableIva")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ResponsableIva");

                            b1.HasKey("EmpresaId");

                            b1.ToTable("Empresas");

                            b1.WithOwner()
                                .HasForeignKey("EmpresaId");
                        });

                    b.Navigation("DatosFiscales")
                        .IsRequired();

                    b.Navigation("Direccion")
                        .IsRequired();
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.Nomina", b =>
                {
                    b.HasOne("GeneradoNominaSystem.Domain.Entities.Empleado", null)
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeneradoNominaSystem.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeneradoNominaSystem.Domain.Entities.PeriodoNomina", null)
                        .WithMany()
                        .HasForeignKey("PeriodoNominaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeneradoNominaSystem.Domain.Entities.PlantillaNomina", null)
                        .WithMany()
                        .HasForeignKey("PlantillaNominaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("GeneradoNominaSystem.Domain.ValueObjects.Dinero", "SubtotalDeducciones", b1 =>
                        {
                            b1.Property<Guid>("NominaId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("SubtotalDeducciones_Moneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("SubtotalDeducciones_Monto");

                            b1.HasKey("NominaId");

                            b1.ToTable("Nominas");

                            b1.WithOwner()
                                .HasForeignKey("NominaId");
                        });

                    b.OwnsOne("GeneradoNominaSystem.Domain.ValueObjects.Dinero", "SubtotalDevengos", b1 =>
                        {
                            b1.Property<Guid>("NominaId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("SubtotalDevengos_Moneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("SubtotalDevengos_Monto");

                            b1.HasKey("NominaId");

                            b1.ToTable("Nominas");

                            b1.WithOwner()
                                .HasForeignKey("NominaId");
                        });

                    b.OwnsOne("GeneradoNominaSystem.Domain.ValueObjects.Dinero", "TotalNeto", b1 =>
                        {
                            b1.Property<Guid>("NominaId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("TotalNeto_Moneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalNeto_Monto");

                            b1.HasKey("NominaId");

                            b1.ToTable("Nominas");

                            b1.WithOwner()
                                .HasForeignKey("NominaId");
                        });

                    b.Navigation("SubtotalDeducciones")
                        .IsRequired();

                    b.Navigation("SubtotalDevengos")
                        .IsRequired();

                    b.Navigation("TotalNeto")
                        .IsRequired();
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.PeriodoNomina", b =>
                {
                    b.HasOne("GeneradoNominaSystem.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.PlantillaConcepto", b =>
                {
                    b.HasOne("GeneradoNominaSystem.Domain.Entities.ConceptoNomina", null)
                        .WithMany()
                        .HasForeignKey("ConceptoNominaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeneradoNominaSystem.Domain.Entities.PlantillaNomina", null)
                        .WithMany("Conceptos")
                        .HasForeignKey("PlantillaNominaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GeneradoNominaSystem.Domain.ValueObjects.Dinero", "ValorPorDefecto", b1 =>
                        {
                            b1.Property<Guid>("PlantillaConceptoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("ValorPorDefecto_Moneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ValorPorDefecto_Monto");

                            b1.HasKey("PlantillaConceptoId");

                            b1.ToTable("PlantillasConcepto");

                            b1.WithOwner()
                                .HasForeignKey("PlantillaConceptoId");
                        });

                    b.Navigation("ValorPorDefecto");
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.PlantillaCotizacion", b =>
                {
                    b.HasOne("GeneradoNominaSystem.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("GeneradoNominaSystem.Domain.ValueObjects.ConfiguracionDocumento", "ConfiguracionDocumento", b1 =>
                        {
                            b1.Property<Guid>("PlantillaCotizacionId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("DecimalesMoneda")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Doc_DecimalesMoneda");

                            b1.Property<string>("EncabezadoPersonalizado")
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT")
                                .HasColumnName("Doc_Encabezado");

                            b1.Property<string>("FormatoFecha")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("TEXT")
                                .HasColumnName("Doc_FormatoFecha");

                            b1.Property<int>("LogoPosicion")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Doc_LogoPosicion");

                            b1.Property<bool>("MostrarFirma")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Doc_MostrarFirma");

                            b1.Property<bool>("MostrarLogo")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Doc_MostrarLogo");

                            b1.Property<bool>("NumeracionAutomatica")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Doc_NumeracionAutomatica");

                            b1.Property<string>("PiePaginaPersonalizado")
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT")
                                .HasColumnName("Doc_PiePagina");

                            b1.Property<string>("PrefijoNumeracion")
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("Doc_Prefijo");

                            b1.Property<int>("SiguienteNumero")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Doc_SiguienteNumero");

                            b1.Property<string>("SimboloMoneda")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("TEXT")
                                .HasColumnName("Doc_SimboloMoneda");

                            b1.Property<string>("TextoFirma")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("Doc_TextoFirma");

                            b1.HasKey("PlantillaCotizacionId");

                            b1.ToTable("PlantillasCotizacion");

                            b1.WithOwner()
                                .HasForeignKey("PlantillaCotizacionId");
                        });

                    b.Navigation("ConfiguracionDocumento")
                        .IsRequired();
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.PlantillaNomina", b =>
                {
                    b.HasOne("GeneradoNominaSystem.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("GeneradoNominaSystem.Domain.ValueObjects.ConfiguracionDocumento", "ConfiguracionDocumento", b1 =>
                        {
                            b1.Property<Guid>("PlantillaNominaId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("DecimalesMoneda")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Doc_DecimalesMoneda");

                            b1.Property<string>("EncabezadoPersonalizado")
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT")
                                .HasColumnName("Doc_Encabezado");

                            b1.Property<string>("FormatoFecha")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("TEXT")
                                .HasColumnName("Doc_FormatoFecha");

                            b1.Property<int>("LogoPosicion")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Doc_LogoPosicion");

                            b1.Property<bool>("MostrarFirma")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Doc_MostrarFirma");

                            b1.Property<bool>("MostrarLogo")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Doc_MostrarLogo");

                            b1.Property<bool>("NumeracionAutomatica")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Doc_NumeracionAutomatica");

                            b1.Property<string>("PiePaginaPersonalizado")
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT")
                                .HasColumnName("Doc_PiePagina");

                            b1.Property<string>("PrefijoNumeracion")
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("Doc_Prefijo");

                            b1.Property<int>("SiguienteNumero")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Doc_SiguienteNumero");

                            b1.Property<string>("SimboloMoneda")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("TEXT")
                                .HasColumnName("Doc_SimboloMoneda");

                            b1.Property<string>("TextoFirma")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("Doc_TextoFirma");

                            b1.HasKey("PlantillaNominaId");

                            b1.ToTable("PlantillasNomina");

                            b1.WithOwner()
                                .HasForeignKey("PlantillaNominaId");
                        });

                    b.Navigation("ConfiguracionDocumento")
                        .IsRequired();
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.ProductoServicio", b =>
                {
                    b.HasOne("GeneradoNominaSystem.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("GeneradoNominaSystem.Domain.ValueObjects.Dinero", "PrecioUnitario", b1 =>
                        {
                            b1.Property<Guid>("ProductoServicioId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("PrecioUnitario_Moneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PrecioUnitario_Monto");

                            b1.HasKey("ProductoServicioId");

                            b1.ToTable("ProductosServicios");

                            b1.WithOwner()
                                .HasForeignKey("ProductoServicioId");
                        });

                    b.Navigation("PrecioUnitario")
                        .IsRequired();
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.Cotizacion", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.Nomina", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("GeneradoNominaSystem.Domain.Entities.PlantillaNomina", b =>
                {
                    b.Navigation("Conceptos");
                });
#pragma warning restore 612, 618
        }
    }
}
